### ISSUE TITLE
Checklist To Do UI/UX and minor qol's

### ISSUE THREAD

**Issue by RishaanvB** [RishaanvB/react_quiz#4]
- [x] get all questions in 1 api call
- [x] create cards for each question
- [x] animate all cards into view
- [x] animate/style btn on choice picked
- [x] style correct answer on wrong choice
- [x] animate card out of view on choice pick
- [x] smooth transition between views
- [x] sort by score (backend) and display 10 scores max. in highscore view
- [x] ui notification on sending highscore
- [x] when sending score to highscore disable btn 
- [x] add replay btn and/or highscore view on gamefinish
- [x] material ui?
- [x] disable btn on pick answer
- [x] reset game after starting game when checking highscores
- [x] store token in localStorage
